### ISSUE TITLE
UI Samples link broken or repo not available

### ISSUE THREAD

**Issue by abhishek-adobe** [Adobe-CEP/Samples#101]
The UI Samples (https://github.com/Adobe-CEP/Samples/tree/master/UI_Showcase) URL appears to be broken or the repo's not available. Can anyone fix/remove that?

**Comment by dkstevekwak** [comment]
@abhishek-adobe thanks for reporting the issue. The sample's name has been changed. I have changed the readmes to reflect the change.
705ba27e7d0f81094600d289ba07721af7d0b236
