### ISSUE TITLE
Can't get samples working

### ISSUE THREAD

**Issue by fridzema** [Adobe-CEP/Samples#108]
Hello, 

I would like to dive in adobe extension development but can't get it work.
I am working on OSX 10.14.4 with illustrator 23.0.4. 

I have 'installed' the extensions properly and where loaded in the extension menu. When i click on a extension i just opens and display nothing:
![Screenshot 2019-07-10 at 11 51 28](https://user-images.githubusercontent.com/8180660/60959791-1e4e6c80-a309-11e9-9f64-b023d2dd8c3a.png)

I have setup debug as documented, restarted etc but localhost does also nothing. 

Anyone know where to look?

**Comment by sbaden** [comment]
Did you edit the com.adobe.CSXS file in Preferences to allow unsigned panels to load?

If you're on a Mac type this into the terminal:
defaults write /Users/<username>/Library/Preferences/com.adobe.CSXS.
5.plist PlayerDebugMode 1

**Comment by fridzema** [comment]
@sbaden thanks for your suggestion! I have managed to get it working with the following command(s):
```
// Set debug mode
defaults write com.adobe.CSXS.9.plist PlayerDebugMode 1 && killall -u `whoami` cfprefsd

// Set log level
defaults write com.adobe.CSXS.9.plist LogLevel 6 && killall -u `whoami` cfprefsd
```
