### ISSUE TITLE
How to run without ESTK ?

### ISSUE THREAD

**Issue by pc8181** [Adobe-CEP/Samples#110]
how to run premiere pro script from command line without etk like after effects ?..

is that possible ?.....

download .jsx file from net and not etoolkit in system how to  run this script ?

**Comment by bbb999** [comment]
/Applications/Adobe\ Premiere\ Pro\ CC\ 2019/Adobe\ Premiere\ Pro\ CC\ 2019.app/Contents/MacOS/Adobe\ Premiere\ Pro\ CC\ 2019 /C es.processFile /Users/<username>/Desktop/scriptname.jsx

"C:\Program Files\Adobe\Adobe Premiere Pro CC 2019\Adobe Premiere Pro.exe" /C es.processFile "C:\path\to\script.jsx"
