### ISSUE TITLE
Change duration of MOGRT after adding

### ISSUE THREAD

**Issue by vin-ni** [Adobe-CEP/Samples#112]
## Change duration after adding Mogrt

This is an issue regarding:

- [x] The samples contained within this repo.
- [ ] The documentation contained within this repo.

## Versions

- [x] CEP version(s) used [must be `8.x+` for this repo]:
- [ ] Supported CC app(s) and version(s):

Hello, I'm playing with the sample PPro Script and would like to set the duration of an inserted Mogrt.

Right now I'm doing this, to give the Mogrt a specified duration:

``` javascript
var endTime = newMOGRT.end;
endTime.seconds = endTimeSeconds;
newMOGRT.end = endTime;
```

which cuts the file to the wished duration, but prevents me from making the duration longer in premiere afterwards. Any ideas how I could fix that?

Thanks

**Comment by bbb999** [comment]
I've added your vote to PPro feature request DVAPR-4212165, "Allow for a .mogrt trackItem whose out point has been adjusted, to be re-extended to original duration". 

I can't provide any dates; I've asked that it be considered for our next major release.

**Comment by vin-ni** [comment]
Thanks!
