### ISSUE TITLE
How to check if Adobe Media Encoder is installed?

### ISSUE THREAD

**Issue by HppZ** [Adobe-CEP/Samples#113]

**Comment by bbb999** [comment]
There's no good way. What's the entire workflow, you're trying to support?

**Comment by HppZ** [comment]
I want to call AME to do something, but before that I want to check if AME is already installed.

**Comment by araujohenrique** [comment]
Maybe this is what you are looking for:
BridgeTalk.getStatus("ame")

That I know of the return values could be:
'ISNOTRUNNING'
'ISNOTINSTALLED'
'BUSY'
'IDLE'
'PUMPING'

**Comment by HppZ** [comment]
thanks!
but how to do it by query registry?

**Comment by HppZ** [comment]
where is BridgeTalk.getStatus documented?

**Comment by HppZ** [comment]
found it https://estk.aenhancers.com/index.html
