### ISSUE TITLE
Delete files from a project

### ISSUE THREAD

**Issue by AlexanderSuvorov** [Adobe-CEP/Samples#116]
Hi.

Is there any way to remove the file from the project, or replace it with another file. I want to give a choice to the user of my extension what to do if the imported file already exists in the project.

Thanks.

**Comment by bbb999** [comment]
Which host application(s)?

**Comment by AlexanderSuvorov** [comment]
Premiere Pro in priority. Perhaps in the future this feature will be needed in After Effects too.

**Comment by bbb999** [comment]
var matchingProjectItemsFound = app.project.rootItem.findItemsMatchingMediaPath(newPath, ignoreSubclips);
 
// that will give you an array of projectItems with the same path. 
// If the array is length 0, no matches.

To remove projectItems, put them into a bin (which you can create), then delete the bin.

**Comment by AlexanderSuvorov** [comment]
It works for me. Thank you.
