### ISSUE TITLE
No panel appearing on Premiere 2021 M2 mac

### ISSUE THREAD

**Issue by friendlygiraffe** [Adobe-CEP/Samples#148]
Installed this in the usual place, can select it in the menu, but nothing pops up
![Screenshot 2023-03-03 at 08 48 03](https://user-images.githubusercontent.com/1918661/222675294-e48dcc03-6e09-4a4e-99c5-ae77b47fb643.JPG)
Using M2 Macbook Air with Premiere 2021

The error log says:

_ERROR Signature verification failed for extension com.adobe.PProPanel_

Edit: Fixed, I needed **defaults write com.adobe.CSXS.10.plist PlayerDebugMode 1**

I was using CSXS.9.plist

**Comment by ErinFinnegan** [comment]
CSXS and CEP are the same thing, so you can use this chart: [https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_12.x/Documentation/CEP%2012%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_12.x/Documentation/CEP%2012%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep)

That said, there's a signature verification issue going on at the moment: [https://github.com/Adobe-CEP/CEP-Resources/blob/master/ZXPSignCMD/KnownIssue2024.md](https://github.com/Adobe-CEP/CEP-Resources/blob/master/ZXPSignCMD/KnownIssue2024.md)
