### ISSUE TITLE
HowTo comment in XMPBridge.js is slightly misleading

### ISSUE THREAD

**Issue by johnlouis-swaine-axomic** [Adobe-CEP/Samples#15]
The example for the excellent XMPBridge unfortunately leads to an `Unregistered namespaceURI schema` error when used.

```
 *          // now we're ready to go.
 *          XMPBridge.read('NS_DC', 'title');
 *          
```

Instead the example should probably include reference to the fact that you can get the the namespace URI from Adobe's constants like NS_DC by calling `XMPBridge.toNamespaceURI()`

```
 *          // now we're ready to go.
 *          XMPBridge.toNamespaceURI('NS_DC', function(namespaceUri) {
 *              XMPBridge.read(namespaceUri, 'title');
 *          });
```

**Comment by johnlouis-swaine-axomic** [comment]
345bc11

**Comment by lesavage** [comment]
I have merged in your change. Thank you for your contribution :)

**Comment by johnlouis-swaine-axomic** [comment]
Welcome!
