### ISSUE TITLE
failure to run render()

### ISSUE THREAD

**Issue by KarlBao** [Adobe-CEP/Samples#21]
It runs well when I choose **Window->Extensions->PProPanel (SDK sample panel)** in Adobe Premiere Pro CC 2014.
However, when I'm trying to run it in Extendscript Toolkit CC, there are several errors:
1. on line 424, _app.encoder.setSideCarXMPEnabled(0);_ 
2. when I fix the bug above (to _app.encoder.setSide__c__arXMPEnabled(0);_), there is no error message prompted. But nothing happened when the function  render() runs.

**Comment by bbb999** [comment]
I don't know why your fix would work. ;) 

Confirming: You're setting the target application = PPro CC 2014 in ESTK? Also: Do you have Adobe Media Encoder installed?

**Comment by KarlBao** [comment]
Yes. It runs well when choose the PProPanel in Adobe Premiere Pro CC 2014. The Media Encoder is launched and the file is exported.
Also, all the functions except render() can work when I run in the ESTK. I checked the Data Browser and noticed that the function in Data Browser is *setSidecarXMPEnabled()* instead of *setSideCarXMPEnabled*.

**Comment by bbb999** [comment]
Please write me directly, and give me a broader understanding of what you're trying to do; b b b at adobe dot com
