### ISSUE TITLE
CEP_HTML_Test_Extension do nothing

### ISSUE THREAD

**Issue by espilacopa** [Adobe-CEP/Samples#32]
in illustrator, nothing is visible or nothing happening. 
is it normal ???

**Comment by arthurwei1975** [comment]
It is not normal. Which version/build of Illustrator were you using? Which version of CEP_HTML_Test_Extension were you using? Thanks

**Comment by espilacopa** [comment]
Now it's working, I had to remove the GPU Performance, when it's active
nothing appear.
sorry for the disturbing.

I'm on the last version of both.

Thanks

2015-10-26 13:23 GMT-04:00 GUO WEI <notifications@github.com>:

> It is not normal. Which version/build of Illustrator were you using? Which
> version of CEP_HTML_Test_Extension were you using? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adobe-CEP/Samples/issues/32#issuecomment-151215660>.
>



-- 
Cordialement

Ludovic Piquet
