### ISSUE TITLE
Require not defined!

### ISSUE THREAD

**Issue by mealdy** [Adobe-CEP/Samples#34]
Just updated the PS to the latest version (2015.1 release), and every extension that used some node modules reported this error, why??

**Comment by undavide** [comment]
Hi, have a look at [this article](http://www.davidebarranca.com/?p=2906) for explanation and workarounds.
-Davide

**Comment by kodabb** [comment]
same happens for 2015.3, the article unfortunately didn't help.

**Comment by Jolg42** [comment]
If you have '--enable-nodejs' in the manifest and it's still not working, just make sure that the `ExtensionManifest Version="5.0"` version is `5.0` 😉 I think that below 5, Node.js is not activated for some reason.

**Comment by phlaidback** [comment]
Is it active in version 6?
I cant get this to work in InDesign CEP version 6. 

var fileToUpload = new File([$scope.myPdfBlob], "myfile.pdf");
I have enabled '--enable-nodejs' but get this error:
TypeError: File constructor cannot be called in nwdisabled frame.

Im using angularJS.

**Comment by Jolg42** [comment]
@phlaidback CEP & ExtensionManifest are different. But yes CEP 6 is coming with Node.js.

Maybe your problem is linked to CEP 6.1:

(From the latest CEP Cookbook here https://github.com/Adobe-CEP/CEP-Resources/raw/master/CEP_7.x/CEP_7.0_HTML_Extension_Cookbook.pdf)

> Using Node.js APIs (CEP 6.1)
Node.js APIs are disabled by default
Due to security consideration, node.js APIs are disabled by default (prior to CEP 6.1,
they were enabled by default) both on the extension level and IFrame level.
To enable Node.js APIs:
- Set ExtensionManifest version and RequiredRuntime version 5.0 or higher.
- Specify '--enable-nodejs' in extension manifest. See section Customize CEF
Command Line Parameters for details
- To use Node.js APIs in IFrames, add property 'enable-nodejs' to it and to all its
ancestor IFrames. If any of its ancestors don't have this property specified,
Node.js APIs won't work
<iframe id="xxx" class="xxxxx" enable-nodejs>

**Comment by kodabb** [comment]
Yes I enabled it, and still no node.
For reference this is my manifest.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<ExtensionManifest Version="6.0" ExtensionBundleId="com.bundle.identifier" ExtensionBundleVersion="1.0.0" ExtensionBundleName="My panel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <ExtensionList>
        <Extension Id="com.bundle.identifier" Version="10.3.0" />
    </ExtensionList>

    <ExecutionEnvironment>
        <HostList>
            <Host Name="PPRO" Version="[9.1,11.9]" />
        </HostList>
        <LocaleList>
            <Locale Code="All" />
        </LocaleList>
        <RequiredRuntimeList>
            <RequiredRuntime Name="CSXS" Version="6.0" />
        </RequiredRuntimeList>
    </ExecutionEnvironment>

    <DispatchInfoList>
        <Extension Id="com.bundle.identifier">
            <DispatchInfo>
                <Resources>
                    <MainPath>./index.html</MainPath>
                    <ScriptPath>./bundle.jsx</ScriptPath>
                </Resources>

                <Lifecycle>
                    <AutoVisible>true</AutoVisible>
                </Lifecycle>

                <CEFCommandLine>
                    <Parameter>--enable-media-stream</Parameter>
                    <Parameter>--mixed-context</Parameter>
                    <Parameter>--allow-file-access</Parameter>
                    <Parameter>--allow-file-access-from-files</Parameter>
                    <Parameter>--enable-nodejs</Parameter>
                </CEFCommandLine>

                <UI>
                    <Type>Panel</Type>
                    <Menu>Bundle</Menu>
                    <Geometry>
                        <Size>
                            <Width>480</Width>
                            <Height>480</Height>
                        </Size>
                    </Geometry>
                </UI>
            </DispatchInfo>
        </Extension>
    </DispatchInfoList>
</ExtensionManifest>
```

**Comment by bbb999** [comment]
CEP HTML successfully uses Node.js, in PPro. Perhaps start from that sample?

I haven't had anyone report continued problems, after working through Davide Barranca's excellent post on the subject: http://www.davidebarranca.com/2015/12/html-panel-tips-19-cc2015-1-cep6-1-node-js-fixes/

**Comment by phoroszowski** [comment]
Move <CEFCommandLIne> component into <Resources> the sample needs to be corrected.

**Comment by Jolg42** [comment]
@phoroszowski 👍 by the way the latest sample is here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_7.x/Samples/CEP_HTML_Test_Extension-7.0

**Comment by phoroszowski** [comment]
Sorry.. I tend to live in the Premiere world. I meant the PPRO sample which is kodabb's probably starting place:

https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/CSXS/manifest.xml

**Comment by Jolg42** [comment]
@phoroszowski Yes but the CEP_HTML_Test_Extension-7.0 is more up to date I think. So maybe it's better to take the CEP important part from this one and the PPRO from the other.

By the way the CEP_HTML_Test_Extension-7.0 is compatible with every apps including PPRO.

**Comment by bbb999** [comment]
For PPro API usage, refer to PProPanel. For modern web frameworks and purdy HTML, refer to CEP HTML Test Extension.
