### ISSUE TITLE
Premiere pro getValue for Position doesn't work at all! Fires an exception

### ISSUE THREAD

**Issue by anastasiuspernat** [Adobe-CEP/Samples#44]
Premiere Pro CC2017 bug here.

If you try to walk through all video clips of app.project.activeSequence and then walk through its components until you reach "AE.ADBE Motion" which corresponds to Rotation, Opacity etc. And then try to change the corresponding property with the name "Position" or just call getValue() of it - the exception "Bad argument" fill fire.

There's no such problem with Opacity for example. Seems position is a vector value and getValue should work some other non-documented way? There's nothing in Samples about that. Can you help?

Thank you!

**Comment by bbb999** [comment]
Perhaps (I'll have a look), though not all parameter types are modifiable.

**Comment by bbb999** [comment]
Confirmed; Position (and other multi-dimensional param types) are not supported, in 11.0.
