### ISSUE TITLE
how to create extension

### ISSUE THREAD

**Issue by kuldeep142857** [Adobe-CEP/Samples#45]
Can you please tell me how you build your extensions?
After making your extension, if you modify your code ,then how do you see the output?
How do you see output in developing stage ?

**Comment by bbb999** [comment]
How I build: Copy PProPanel, use Sublime Text to change 'PProPanel' to 'NewPanelName', and trim out all the stuff I don't need. :) 

How I see changes, and output: 
Here's a [screen video](https://www.dropbox.com/s/lwo8jg0klxkq91s/walkthru.mp4) on how to debug PPro panels at the ExtendScript and JavaScript levels.

**Comment by kuldeep142857** [comment]
Hi
Can you please explain, what is PProPanel?
Where do you install/find it?
And how to connect extension code to it?

Thanks
