### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by freddieline** [Adobe-CEP/Samples#46]
I get this error in the browser debugger when I open up the Flickr extension in Photoshop. I am using Adobe Photoshop 2015.5

I have already:

1) Added my Flickr API key to FLICKR_API_KEY in main.js

2) Enabled Node.js in the Manifest.xml file between <Resources> and <MainPath>

<CEFCommandLine>
    <Parameter>--enable-nodejs</Parameter>
</CEFCommandLine>

**Comment by ashryanbeats** [comment]
This sample was recently updated as part of a big update to this repo. Please feel free to reopen if you're still having trouble.

https://github.com/Adobe-CEP/Samples/tree/master/Flickr
