### ISSUE TITLE
Premiere api-doc incorrectly lists Sequence.setPlayerPosition() as accepting "00:00:00:00"

### ISSUE THREAD

**Issue by funkelodeon** [Adobe-CEP/Samples#47]
The api-doc included with the PProPanel sample code describes the setPlayerPosition method on Sequence as accepting a timecode string of the format 'hh;mm;ss;nn', when in fact setPlayerPosition takes a timecode expressed in _ticks_, as shown in the PProPanel example code.

**Comment by bbb999** [comment]
<sigh> yet another reason to not provide docs. :) Fixed.
