### ISSUE TITLE
Update manifest host versions

### ISSUE THREAD

**Issue by jenstroeger** [Adobe-CEP/Samples#48]
It looks like the host version numbers aren't up-to-date with the latest CC tool versions. E.g. [InDesign should be `Version="[11.0,12.9]"`](https://github.com/Adobe-CEP/Samples/blob/master/CEP_HTML_Test_Extension/CSXS/manifest.xml#L13) or the like.

**Comment by ashryanbeats** [comment]
Thanks @jenstroeger. This should now be addressed for all samples after @dkstevekwak's recent refresh. Feel free to reopen if there's a specific sample where this is still an issue.
