### ISSUE TITLE
Sample extension is not working in IDSN

### ISSUE THREAD

**Issue by jenstroeger** [Adobe-CEP/Samples#49]
This is a follow-up to [this question](https://forums.adobe.com/thread/2260505) that I posted in Adobe's Scripting SDK forum. In short, the [RSSReader](https://github.com/Adobe-CEP/Samples/tree/master/RSSReader) example does not work, in spite of adjusting the `manifest.xml` to

    <Host Name="IDSN" Version="[10.0,12.9]"/>

to match the latest InDesign CC version. I've also set `PlayerDebugMode` to `1` in order to develop the extension, as per documentation. I am able to open the extension's panel but without content; trying to connect the debugger fails as well. I've also switched the logging level to `INFO` but get only an expected

    2017-01-09 13:22:07:567 : INFO  PlugPlug version : 7.0.0.59
    2017-01-09 13:22:07:567 : INFO  LogLevel : 1
    2017-01-09 13:22:07:567 : ERROR Signature verification failed for extension com.adobe.htmlsample.rssreader.panel

![idsn](https://cloud.githubusercontent.com/assets/12053937/21766499/306cac92-d66f-11e6-862e-5d9c93d42353.jpg)

**Comment by venpa** [comment]
You need to either codesign the extension or if you are developing the extension and want to enable the debugging, use debug settings as described at https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_7.x/CEP_7.0_HTML_Extension_Cookbook.pdf.

Refer to the section: "Signing extensions" for codesigning the extension. 
Refer to the section: "Debugging Unsigned Extensions" for debug setup.

**Comment by jenstroeger** [comment]
Thanks @venpa. I don't understand what you mean by “codesign the extension”.

I am trying to build and debug an extension: I already followed the debugging steps, and, as I mentioned above, connecting the debugger did not work. However, because InDesign is able to load and display the extension, I assume that at least *some* of the steps to develop an extension worked.

**Comment by venpa** [comment]
@jenstroeger : Adobe ensures that, production extensions are not tampered by providing the code signing mechanism to the extension developers. On every launch, code sign is verified to ensure that content of extension is not modified. Once you have developed the extension, you need to code sign the extension using the steps mentioned at "Signing extensions" section of the cookbook.

You should have done following step to skip the code sign verification:
`Win`: regedit > HKEY_CURRENT_USER/Software/Adobe/CSXS.7, then add a new entry PlayerDebugMode of type "string" with the value of "1".
`Mac`: In the terminal, type: defaults write com.adobe.CSXS.7 PlayerDebugMode 1 (The plist is also located at /Users/<username>/Library/Preferences/com.adobe.CSXS.7.plist)

**Comment by jenstroeger** [comment]
I did already set the `PlayerDebugMode` to `1` in `com.adobe.CSXS.5.plist`, setting it in `com.adobe.CSXS.7.plist` as well does not change anything.

Please note that InDesign *already* loads the extension and displays the panel, but all content is missing. I would assume that the extension could not even be loaded (because it's not properly code-signed) if the debug mode was not set correctly.

**Comment by bbb999** [comment]
The screenshot you've provided is consistent with CEP behavior, around unsigned extensions; the menu item is displayed, but nothing will happen if the menu item is invoked.

**Comment by jenstroeger** [comment]
@bbb999 Then I don't understand how I am supposed to develop and debug an extension without signing it before every test deployment.

**Comment by bbb999** [comment]
Debug extensions should load and display correctly, when PlayerDebugMode is set. 

Sign it before deploying it to non-development systems.

**Comment by jenstroeger** [comment]
@bbb999 See above, I've set the debug mode already, yet the panel is empty and Chrome is unable to establish a connection.

**Comment by phlaidback** [comment]
Do you have a .debug file in the extension folder?
You also need to apply debug mode:

To run an unsigned extension in the target host application (which you typically need to do for debugging) you must set an OS-specific flag. The location of this flag depends on which version of the host application you are targeting for your extension. In 

Windows: 
1. Choose Run from the Windows Start menu, and enter regedit to open the registry editor. 
2. Navigate to the key HKEY_CURRENT_USER\Software\Adobe\CSXS.4\… 
3. Change value for key PlayerDebugMode to 1 to enable or to 0 to disable the debug mode. 
4. Close the registry editor. 

In Mac OS: 1. Navigate to the folder /Library/Preferences/… 
2. Find the PLIST file: com.adobe.CSXS.4.plist 
3. Open this file with the XCode Property List editor, or the PlistBuddy command-line tool. 
4. Change value for the key PlayerDebugMode to 1 to enable or to 0 to disable the debug mode. 
5. Save the file. NOTE: If this file is read-only, you must add write permission for the user before you can update it. To do this, right click on the file and select Get Info > Sharing & Permissions.

You might need to restart the computer as well to make the changes take effect.

Regards
/ Pontus

_______________________________________________
Laidback Solutions AB 
Norrköping • Sweden

Direct: +46 (0)11-12 84 39
Office: +46 (0)11-12 75 80
Mobile: +46(0)705-334307

www.laidbacksolutions.se <http://www.laidbacksolutions.se/>
_______________________________________________

**Comment by bbb999** [comment]
I don't have InDesign installed. I added PPro to RSSReader's manifest, and can now successfully invoke RSSReader from within PPro, and debug it in Chrome (localhost:8010).

**Comment by bbb999** [comment]
Fails on line 1 of index.html:
 var http = require('http');

I'm not sure RSSReader's Node.js usage is functional...

**Comment by jenstroeger** [comment]
@phlaidback See previous comments in this thread: I did that already, reboot did not help either.

@bbb999 It looks like [node’s http module](https://nodejs.org/api/http.html) is *not* part of the sample extension package ([node modules](https://github.com/Adobe-CEP/Samples/tree/master/RSSReader/node_modules) of the extension), true. However, even a minimal extension like the attached one does not show any panel content.

Minimal extension example Foo: [foo.zip](https://github.com/Adobe-CEP/Samples/files/694001/foo.zip) This should show `Hello world` in the panel, but doesn’t.

**Comment by venpa** [comment]
@jenstroeger : Can you please share the logs based on the section "Where are the Log Files"? Please ensure to set the log level to 6. As per your first post, launch is failing due to code signature which is why i was giving options for skipping the code sign.

**Comment by phlaidback** [comment]
The Foo plugin works without any problems for me.
Do you place the plugin in the following folder?
~/Library/Application Support/Adobe/CEP/extensions/

**Comment by jenstroeger** [comment]
After adding `PlayerDebugMode` in _all three_ files (`com.adobe.CSXS.{5,6,7}.plist`) and a reboot, everything started to work.
