### ISSUE TITLE
examples does not work in AE CC 2014.1

### ISSUE THREAD

**Issue by francoisgfx** [Adobe-CEP/Samples#5]
either by modifying the manifest, the panels are not created. Those samples does not work with AE.

**Comment by xzyfer** [comment]
> They show up in the Extension menu (except for the ones I didn't change the manifest), but when I click on them, nothing happen. 

I'm experiencing this same issue.

> enabled loading of debug panels, via RegEdit.exe or .plist editing

I've done this as per the instructions on the read me. Still experiencing the same issue after quitting and restarting Illustrator.

Is there something I need to do to get Illustrator to reload the plist file?

**Comment by lesavage** [comment]
What platform are you on?

**Comment by xzyfer** [comment]
OSX Mavricks. Illustrator CC 2014.1.1 18.1.1.

**Comment by lesavage** [comment]
The plist can get cached so can you try killing the cfprefsd process. It will restart automatically.

**Comment by xzyfer** [comment]
> The plist can get cached
 
Cool, that's what I figured.

>... killing the cfprefsd process. It will restart automatically.

Worked like a charm, thank-you!
