### ISSUE TITLE
I'm unable to open PProPanel in Premiere Pro (with Mac Sierra)

### ISSUE THREAD

**Issue by Marcuzzz** [Adobe-CEP/Samples#50]
I'm unable to open PProPanel in Premiere Pro CC 2015 & 2017 with Mac Sierra
I can see the extension.  []https://postimg.org/image/86und3u0x/ But nothing happens. 
`defaults write /Users/marcbookpro/Library/Preferences/com.adobe.CSXS.6.plist PlayerDebugMode 1` Has been applied. Other extensions I've created don't work either... 
Property Explorer does work.

**Comment by bbb999** [comment]
Have you rebooted since applying PlayerDebugMode? OS X > 10.10 (I think) don't recognize the new .plist setting until Finder is restarted.

**Comment by Marcuzzz** [comment]
Yes. I've rebooted and I even disabled: System Integrity Protection. `csrutil disable`
I also remove .debug from the extension folder. 
Mac Console spitting out a lot of garbage... So I'm not sure if it's related:
default	22:23:45.164792 +0100	securityd	New client connection 0x7fad8ac37a10: 53831 501

**Comment by bbb999** [comment]
Hrmmn...

Confirming: Is /PProPanel inside /Library/Application Support/Adobe/CEP/extensions?

**Comment by Marcuzzz** [comment]
Yes.

**Comment by bbb999** [comment]
So much for the easy fix. :) 

Thrill-seeker that I am, my panel dev system is running 10.12.2, with no apparent issues; I remain hopeful we can figure this out. 

Did you happen to edit any of the files in the /PProPanel directory, with a rich text editor?

When did your own panels last load? 
What's changed in the configuration, since then? 
How were your installed Premiere Pro apps, installed? CC app, CC Packager, other...?

**Comment by Marcuzzz** [comment]
Okay I found a workaround. If you sign and install the extension it works.
Create a certificate:
`./ZXPSignCmd -selfSignedCert US California Adobe "Bruce Bullis" password certificate.p12`

Create a package:
`./ZXPSignCmd -sign panelDir/ PanelName.zxp certificate.p12 password -tsa https://timestamp.geotrust.com/tsa`

Install package:
`ExManCmd --install ppro.zxp `

**Comment by bbb999** [comment]
I'm glad installing the signed panel works, but you'll still need to load UNsigned panels...

Please write me at my day job [bbb@adobe.com], and we'll arrange further investigation.

**Comment by Marcuzzz** [comment]
Basically it needs:
a folder META-INF with signatures.xml
and a file: mimetype 
Developing on Mac Sierra is a big challange because any changes on a file in the extension makes the hash invalid

**Comment by Marcuzzz** [comment]
Okay found the problem, permissions of the "com.adobe.CSXS.6.plist" file were incorrect.
