### ISSUE TITLE
Permiere JS library?

### ISSUE THREAD

**Issue by drlukeangel** [Adobe-CEP/Samples#51]
Hello this isn't issue more of a question. 
I am looking for a Adobe Premiere js libary i can use to build a import or project? 
I make alot of elearning classes i 60 sequences so i just wrote a a script to built the premiere sequences. standard stuff intro/main/outro and put all the files in the the chapter-> sequence -> bin. 
I built reverse engineered hack to build my own adobe premiere import using the final cut pro spec I just stumbeled to these samples. do you have a legitmimate librarby I can use? i can push my stuff to the web service and pull it in json/xml if that is easier.

**Comment by bbb999** [comment]
There is no JS library. PPro's API is in ExtendScript.

Your panel is welcome to use whatever web framework / JS library you like.

**Comment by drlukeangel** [comment]
Do you know of any ways to generate a premiere pro sequence using js? Or in  general instead of me hacking one together?  Seems like this would be a solved problem.

**Comment by bbb999** [comment]
Yes, it is a solved problem; PPro's API is in ExtendScript, which can be _invoked_ from JavaScript.

Create a sequence from a preset: https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/Premiere.jsx#L359

Import a sequence, via FCP XML: https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/Premiere.jsx#L215

Manipulate sequence details: https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/Premiere.jsx#L252

https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/Premiere.jsx#L1072
