### ISSUE TITLE
uncaught exception to run app.encoder.encodeFile()

### ISSUE THREAD

**Issue by isfrav** [Adobe-CEP/Samples#54]
In Adobe Premiere Pro CC 2017 v**11.1.1** an uncaught exception appears when executing the function app.encoder.encodeFile();
(In previous versions it worked fine)

**Comment by bbb999** [comment]
Works fine here...

Please send a snippet that reliably reproduces the issue, to my day job address [b b b at adobe dot com], and I'll have a look.

**Comment by bbb999** [comment]
Reproduced; annoying! We're tracking the issue as DVAPR-4202492, "app.encoder.encodeFile() generates an unhandled exception; same code works fine in 11.0.2." I put your email in the bug report; we'll keep you informed of our progress.
