### ISSUE TITLE
PProPanel sample - Unable to load

### ISSUE THREAD

**Issue by nanandn** [Adobe-CEP/Samples#67]
Hi

I am a beginner. I am just starting to learn how to write extensions/panels. I am using PPRO v12.0.
I copied the PProPanel sample to ~//Library/Application Support/Adobe/CEP/extensions directory. Changed the manifest.xml files 

```
<ExecutionEnvironment>
		<HostList>
			<Host Name="PPRO" Version="12.0" />
		</HostList>
		<LocaleList>
			<Locale Code="All" />
		</LocaleList>
		<RequiredRuntimeList>
			<RequiredRuntime Name="CSXS" Version="8.0" />
		</RequiredRuntimeList>
	</ExecutionEnvironment>
```

When I open Primiere Pro, I don't see the panel in Windows -> Extensions menu. 

Am I missing something here? How do I get the panel to show up?

Thanks
Anand

**Comment by mBeierl** [comment]
Hi,

just to make sure: You only changed the ExecutionEnvironment part of the original manifest.xml to your snippet and now the whole file, right?

**Comment by QStack** [comment]
Hi,

did you follow the instructions to enable debugging of unsigned extensions?
See here [Debugging Unsigned Extensions](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions)

**Comment by undavide** [comment]
FYI, Version="8.0" in `<RequiredRuntime>` and `<ExtensionManifest>` (same version, as we've always done, matching CEP version) makes the panel disappear from the Extensions list in Photoshop

**Comment by nanandn** [comment]
Thank you all for your response/help. Yes. I think using Version=8.0 seems to be the problem. I was using 8.0, partly because the matrix in https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions says for CC 2018 The PPRO version is 12.0 and CEP is 8.0. I could not find the manifest XSD for 8.0. I was using the 7.0 XSD. 

Now I have the Runtime version as 7.0 and the ExtensionManifestVersion as 7.0. Seems to work. 

In ExtensionManifest, there is a ExtensionBundleVersion and a Version. What is the ExtensionBundlerVersion?

A couple of more questions...

- Is there a way to re-load the extension without having to reload the host application? During development, I keep making changes and copying it to the User's extension directory (~/Libraray/Application Support/Adobe/CEP/extensions, using gulp and watch). But it seems like I need to re-launch PPRO. Is there way to re-load the extension?

- The next step I want to do is to interact with my backend system, to get some data via REST APIs. Is there any resource/documentation/samples on how to do this?

- I haven't looked at the SDK APIs completely yet. But is there is a way to hook into the project creation flow and add custom fields in the project creation dialog and store them along with the PPRO project metadata?

Once again, thanks for all the help. 

Regards,
Anand

**Comment by bbb999** [comment]
Reloading extension: See PProPanel's 'refresh' button.

There's nothing in PProPanel about REST APIs; the other samples in the repo may provide examples.

There is no way to hook into PPro's own project creation. PProPanel shows how to modify PPro's private project metadata.

https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/PPRO/Premiere.jsx#L737

**Comment by nanandn** [comment]
@bbb999 Thanks. I should have looked at the example more closely :-)
I was able to get the refresh working. Will look at the other examples.

Anand
