### ISSUE TITLE
Is Adobe CEP support Angular2

### ISSUE THREAD

**Issue by mds-charu** [Adobe-CEP/Samples#68]

**Comment by timc3** [comment]
It should, as it generally supports most JavaScript.

**Comment by mds-charu** [comment]
Thanks, I am now able to develop plugins using Angular2 and Angular4

**Comment by mBeierl** [comment]
From the [Extension Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef):

> CEP HTML engine is based on Chromium Embedded Framework version 3 (CEF3). You can find more information about CEF here.

You can use any javascript frontend library you want. There is no limitation or specific "support" delivered by CEP.
