### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by nanandn** [Adobe-CEP/Samples#69]
What is the right forum to ask questions about CEP, extendscript, writing HTML panels, for Premiere pro?

Anand

**Comment by undavide** [comment]
The new [Extensions / Add-Ons Development Forum](https://forums.adobe.com/community/creative_cloud/add-ons/extensions) is probably the best fit. It is meant as a replacement of the old Extension Builder 3 forum, which was the place where most discussions about CEP were hosted in the past.

**Comment by jimmcnulty41** [comment]
Could this forum be linked in a [Code of Conduct](https://github.com/Adobe-CEP/Samples/community) for this project?

**Comment by ashryanbeats** [comment]
The forum is now linked in the new [issue template for this repo](https://github.com/Adobe-CEP/Samples/blob/master/ISSUE_TEMPLATE.md).
