### ISSUE TITLE
[PPro 2018] Change sequence marker name is not working

### ISSUE THREAD

**Issue by fcarrilLB** [Adobe-CEP/Samples#70]
In the PPro sample, rename the sequence marker is not working in PPro 2018 (in PPro 2017 it works).

Steps to reproduce:
* Open PPro sample extension
* Click in the "Add sequence markers" button
* The marker names are empty

JSX code:
https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/PPRO/Premiere.jsx#L192

**Comment by bbb999** [comment]
Yep; known issue. It's being investigated for an ASAP fix.
