### ISSUE TITLE
PProPanel doesn't work

### ISSUE THREAD

**Issue by AXXOrganic** [Adobe-CEP/Samples#71]
Hi There,

it lists in the Windows->Extension Submenu on Mac inside PPRO.
But nothing happens when selecting the menu item.

Were you aiming to show folks how to insert a menu item in a Menu ? Or is a panel supposed to open.

One last question. If those panels are so powerful, how come 90% of all sample code never works,
Including this one ?

**Comment by bbb999** [comment]
Sounds like you didn't enable the loading of debug extensions, as detailed in PProPanel's readme.

Hundreds of customers use panels every day, for their production workflows; sorry you're having trouble.

**Comment by AXXOrganic** [comment]
Hi and thanks for your reply.

1. We did follow your directions 100%. Used Terminal Defaults write to add the dict entry on both the
com.adobe.CSXS.7.plist and com.adobe.CSXS.8.plist and double checked that the writes had taken place.

The Extension shows in the Window->Extension menu item. but nothing happens when selecting it.
This is on Mac 10.12 with PPRO 11.1.2 and PPRO 10.4 on two independent systems.

Just to double check that I did not fool my self, I asked two of our lead developers to try the same thing. Download your PPRO Panel sample and get it to work by following your instructions. Both had exactly the same thing happen as I. So I take that either the instructions aren't correct or something is going on on the Mac Platform which you were not anticipating.

We do low-level OpenCL/C/C++/OBC/SWIFT/JS Programming and are used to follow directions from frameworks far more cloudy than a JS Scripting Framework and we just cannot get it to work...

We are doing a Custom UI inside of PPRO as frontend for our OpenCL Algorithm, currently drawing with DRAWBOTs and Cocoa Views but were looking to see if we could implement our Custom Sliders via the HTML5 Panel Extension.

But so far, none of the three of us were able to even get a Panel Extension to even show up. 

Perhaps we are missing the total obvious :-) And I sure would appreciate the help 

Thanks

**Comment by bbb999** [comment]
Did you restart Finder after changing the .plist setting? 

Both had the same experience: bizarre. This sample and the readme instructions work great, on dozens/hundreds of systems.

Write me at my day job [b b b at adobe dot com], and let me know exactly where your experience departs from that described in the readme.

**Comment by dustball** [comment]
I had the same problem.  The solution was to make sure the .plist file is owned by the username in question and not root.  I am not the only one encountering this, you may want to update the main README.
