### ISSUE TITLE
[PPro 2018] Clip Markers not working.

### ISSUE THREAD

**Issue by jmsfcb** [Adobe-CEP/Samples#73]
Still not working in PPro2018. Possibly related to this [this bug.](https://forums.adobe.com/message/9946512#9946512)

https://github.com/Adobe-CEP/Samples/blob/01ea9a0b8501ff20643ffb7da60142bb8c2cc1d6/PProPanel/jsx/PPRO/Premiere.jsx#L743-L745

**Comment by bbb999** [comment]
The bug was introduced in 12.0, so I'm not sure what "still" not working means.

**Comment by melMass** [comment]
@bbb999 Bruce, do you know if this is still an issue (or introduced) in 2021?

The following don't work, end is ignored in all cases:

```javascript
var marker = activeSequence.markers.createMarker(clip.start.seconds)
marker.name = "shot_" + id;

marker.end.ticks = clips[clip].end.ticks;
// This does not work either
// marker.end = clips[clip].end.seconds;
// marker.end = clips[clip].duration.seconds;
```
