### ISSUE TITLE
Enabling Node.js in PProPanel sample crashes the debugger

### ISSUE THREAD

**Issue by fcarrilLB** [Adobe-CEP/Samples#74]
**Problem:** The extension refreshes by itself after resume the script execution

**To reproduce the bug, first you need to enable Node.js in PProPanel:**
- Change `ExtensionManifest` `Version` from `4.0` to `6.0`
- Move `CEFCommandLine` from `DispatchInfo` to the `Resources` tag

manifest.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ExtensionManifest Version="6.0" ExtensionBundleId="com.adobe.PProPanel" ExtensionBundleVersion="11.1"
ExtensionBundleName="Premiere Pro sample panel"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ExtensionList>
		<Extension Id="com.adobe.PProPanel" Version="10.3.0" />
	</ExtensionList>
	<ExecutionEnvironment>
		<HostList>
			<Host Name="PPRO" Version="9.0" />
		</HostList>
		<LocaleList>
			<Locale Code="All" />
		</LocaleList>
		<RequiredRuntimeList>
			<RequiredRuntime Name="CSXS" Version="6.0" />
		</RequiredRuntimeList>
	</ExecutionEnvironment>

	<DispatchInfoList>
		<Extension Id="com.adobe.PProPanel">
			<DispatchInfo >
				<Resources>
					<MainPath>./index.html</MainPath>
					<ScriptPath>./PProPanel.jsx</ScriptPath>
					<CEFCommandLine>
						<Parameter>--allow-file-access</Parameter>
						<Parameter>--allow-file-access-from-files</Parameter>
						<Parameter>--enable-nodejs</Parameter>
					</CEFCommandLine>
				</Resources>
				<Lifecycle>
					<AutoVisible>true</AutoVisible>
				</Lifecycle>
				<UI>
					<Type>Panel</Type>
					<Menu>PProPanel (SDK sample panel)</Menu>
					<Geometry>
						<Size>
							<Height>300</Height>
							<Width>180</Width>
						</Size>
					</Geometry>
				</UI>
			</DispatchInfo>
		</Extension>
	</DispatchInfoList>
</ExtensionManifest>
```

Steps to reproduce the bug:
- Add a breakpoint in the Chrome debugger
- Trigger an action to execute the code with the breakpoint
- The script execution is stopped
- Resume the execution (F8) or Step over/into the next function (F10/F11)
- The extension refreshes by itself, preventing the correct debugging for the extension

Enviroment to reproduce the bug:
- CEP 8.x (Premiere Pro 2018)
- Windows 10
- Extension with Node.js enabled
- Breakpoint in any JavaScript code

Notes:
- I couldn't reproduce it on Mac

**Breakpoint**
![ppropanel-debugger-windows](https://user-images.githubusercontent.com/22244773/33222606-44deb26a-d137-11e7-9ede-5a9bc2f60e3f.png)

**After resume the execution, the extension reloads automatically**
![ppropanel-debugger-windows-2](https://user-images.githubusercontent.com/22244773/33222607-45008e08-d137-11e7-853c-e97f612b4ed9.png)

**Comment by bbb999** [comment]
Just turning on Node.js is unlikely to succeed; your result is, unfortunately, unsurprising.

Can you get CEP HTML Test Panel 1 to successfully detect whether Node.js is enabled?

**Comment by fcarrilLB** [comment]
@bbb999 with the current `manifest.xml` Node.js is not enabled, if in the console I try to get any Node.js module, `window.require` and `window.cep_node` are undefined (in http://localhost:7777)

In the other hand if I change the `manifest.xml` as I described in my previous comment, I can get any Node.js module without problem because `window.require` and `window.cep_node` exist but, enabling this produces the described bug

**Comment by venetak** [comment]
Hello, I have the same issue, can you please share if you managed to fix it?

**Comment by fcarrilLB** [comment]
@venetak I haven't found a solution for Windows yet, if you have a Mac, use it for the debugging.

**Comment by venetak** [comment]
@fcarrilLB Thank you.

**Comment by nbabanov** [comment]
@bbb999 Do we have any progress on this? Where is the best place to raise the issue, so that Adobe considers it?

**Comment by nbabanov** [comment]
@bbb999 NodeJS works in any project. The problem with it is, that it breaks the CEP Chrome remote debugging. It is not related exclusively to any sample. The problem is in CEP.

**Comment by bbb999** [comment]
> The problem is in CEP.

You may be right. This problem report is specific to PProPanel. 

No PPro panel developer has reported problems debugging Node.js. 

If the problem is reproducible in CEP HTML Test Panel, we can have the CEP team investigate further.
