### ISSUE TITLE
simpledissolve and Ps CC 19

### ISSUE THREAD

**Issue by pasbi** [Adobe-CEP/Samples#77]
Is the simpledissolve extension compatible with the most recent Photoshop CC (19.1.1)?
I did not find any information about how to install the extension, so I copied the three folders `SimpleDissolveUI`, `SimpleDissolveScripts`, `SimpleDissolveApplyFilter` into 
`%AppData%\Roaming\Adobe\CEP\extensions\`.

The readme implies that a menu item "Simple Dissolve Extension…" will show up in the Filter menu, however, no such menu item appears after restarting Photoshop.

**Comment by undavide** [comment]
I would say that the content of `SimpleDissolveScripts` needs to go into the Photoshop's `/Presets/Scripts` folder.
