### ISSUE TITLE
Exchange Example needs to be updated or removed

### ISSUE THREAD

**Issue by ErinFinnegan** [Adobe-CEP/Samples#78]
Now that the Exchange has relaunched we need to update or remove outdated examples.

https://github.com/Adobe-CEP/Samples/tree/master/ExchangeExample

**Comment by ashryanbeats** [comment]
This was removed as part of @dkstevekwak's recent update.

https://medium.com/adobetech/use-cep-samples-to-accelerate-creative-cloud-extension-development-b9ea0a3aa989
