### ISSUE TITLE
Where is detailed docs about Premiere Pro Scripting DOM API?

### ISSUE THREAD

**Issue by YoungsooJang** [Adobe-CEP/Samples#80]
Hi, I'm making customized panel for Premiere Pro CC 2018.
I expect my panel can perform a few functions:
1. split(cut) a track(both audio and video) into 2 subtracks by time parameter
  ex) There are simply two panels, my panel and built-in track panel. A video track is already imported in track panel. I want split this track into 2 subtracks at 10 sec.
2. change the start time of a track
  ex) A video track is already imported in track panel. I want move this track backward or forward 10 sec.

Can I achieve these two goals through CEP?
I'm looking around Premiere Pro Scripting DOM API (which includes classes such as App, TrackItem, ...).
Now, I'm referring to Object Model Viewer that can be reached from ExtendScript Toolkit CS5. But it seems like unfriendly and poor, so I want detailed docs about these. Can anyone give me the links or docs?

**Comment by YoungsooJang** [comment]
@bbb999 Thank you for your answer. This link is exactly what I'm looking for. Have a nice day!

**Comment by louwjlabuschagne** [comment]
@YoungsooJang did you manage to implement a function that cuts at the playhead?

I'm also looking into implementing this functionality.

**Comment by Fougl** [comment]
@bbb999 i have difficulty figuring out how to modify start and end times of trackitems. In the documentation from the link you posted it is not clear how to incorporate time parameter.
Thanks

**Comment by bbb999** [comment]
Try setting the values _within_ the Time object, rather than replacing the Time object.

**Comment by Fougl** [comment]
Thanks for the quick reply. I am really new to this. I just have to do it for one of my pet projects. So bear with me. I have the following to get the start time object:
app.project.sequences[0].videoTracks[1].clips[0].start
and the following for getting it in seconds:
app.project.sequences[0].videoTracks[1].clips[0].start.seconds

So i want to do it within time object somehow. I just do not know how. Also in the https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/PremierePro.14.0.d.ts I can only see that it is read only.

**Comment by Fougl** [comment]
Oh yes. I managed to do it 
app.project.sequences[0].videoTracks[1].clips[0].start=30

Thanks for the quick response again.  I am amazed by the comunity. Best
