### ISSUE TITLE
Javascript core functions in extension failing on some machines, working fine on others

### ISSUE THREAD

**Issue by arobots** [Adobe-CEP/Samples#84]
My Premiere panel works perfectly on some machines, but on others, the script trips up on core javascript functions - I get errors like ".indexOf() is not a function" or ".filter() is not a function" when doing some operations on arrays inside the JSX. Why would that happen on some machines but work on others if the files inside the extension folders are identical and all machines have Premiere up to date?

**Comment by bbb999** [comment]
I’ll guess that your panel is depending on an ExtendScript JSON object. This object is only available, while some Adobe panel is open; AVOID.

Here, I must apologize for whomever within Adobe decided “let’s sporadically provide an ExtendScript object, while providing no indication that it is ephemeral and unreliable” was a good idea; it wasn’t.

Instead, do JSON stuff in your panel’s JavaScript layer.



-bbb

**Comment by Silly-V** [comment]
I've used JSON inside ExtendScript for millenia; it's not so bad, but it appears from the looks of it like there was code ran on some of the machines to pre-fill the necessary ".indexOf()" code and not on others. Once some extendscript puts in the methods to add to the ES3 methods, it will last for long time, even giving impression that the code comes with those by default if you forget about it.
Try to have some users restart their Premier or machines entirely to see if ones which appeared to be working now also do not. This would be my test for above scenario.

**Comment by arobots** [comment]
Yeah, I figured it was because of Extendscript's age since those array functions were added to later version of ECMA - I just never imagined it would be a problem since it worked in some cases. I did some sloppy Array.prototype stuff to add the functionality as a quick fix, but will make sure to try to isolate this to the panel layer in the future.

**Comment by Silly-V** [comment]
It may be possible other extensions or scripts ran on those machines also leave the prototypes in. If you are able to confine your higher-level functions to the panel javascript, that will solve it, but you could also have just the necessary code at the top of your jsx to ensure the methods you need, will work.

**Comment by undavide** [comment]
In Photoshop, I've never run into ExtendScript code that was able to understand natively `JSON`, nor `indexOf`, nor any other ES5 syntax. ExtendScript is based on JS specs which pre-date 2009, so it is safe to assume (using the words of an Adobe engineer) that if some of those things work, it's by pure chance. I would suggest to embed [ES5 shims](https://github.com/es-shims/es5-shim).

**Comment by MaxJohnson** [comment]
Chiming in here with to expand on shims... My guess is that some other extension or script is using a shim to modify the global prototypes before your script is being loaded. Then you get the benefit of those modifications only on the machines with those extensions installed as well.

Betcha @undavide  's recommendation of embedding that ES5 shim will solve your problem (and possible break some other extension)
