### ISSUE TITLE
Progressbar not works in Windows.

### ISSUE THREAD

**Issue by ten-A** [Adobe-CEP/Samples#89]
We can use the Script UI in Extensions, Progressbar also works fine in OSX. However, When we call ScriptUI's panel or window from CEP side, we got blank window in Windows. Definitely, Works fine same code when call from ESTK.

Please refer below article, You can find some screenshot and test extension project.

https://forums.adobe.com/thread/2505027

Ten A

**Comment by dkstevekwak** [comment]
Please report the issue in the CEP-resource repository. This issue log is for samples only.
