### ISSUE TITLE
PProPanel shows a non-working and misleading way to enable Node.js

### ISSUE THREAD

**Issue by matangover** [Adobe-CEP/Samples#92]
PProPanel is misleading. It contains the `--enable-nodejs` directive in the [manifest](https://github.com/Adobe-CEP/Samples/blob/b0f2f7d433e94f40b80bebc2307c8d271d31f483/PProPanel/CSXS/manifest.xml) but that directive does nothing, because:
 1. `CEFCommandLine` is in the wrong place. It's under `<DispatchInfo>` instead of under `<Resources>`.
 2. `<ExtensionManifest Version="4.0">`, instead of "5.0" or higher (but not "8.0" because then your extension is not loaded, of course...).

If we copy the sample to create our own panel, we expect Node.js to work since `--enable-nodejs` is defined. However, it doesn't work. This can be verified by debugging in Chrome (`cep_node is undefined`) and also by enabling verbose logging, opening `~/Library/Logs/CSXS/CEP8-PPRO.log` and seeing that CEFCommandLine is not displayed for PProPanel.

Please add documentation of minimum `Version` and `CEFCommandLine` location in manifest. I just wasted a whole day on this. The sample [here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md) is correct.

Related: #74 

## Topic

This is an issue regarding:

- [X] The samples contained within this repo.

## Versions

- [X] CEP version(s) used [must be `8.x+` for this repo]: 8.0
- [X] Supported CC app(s) and version(s): PPro 12.0

**Comment by matangover** [comment]
@bbb999 why closed?

**Comment by bbb999** [comment]
Because I just made the requested changes...?

**Comment by matangover** [comment]
Ahh sorry where did you make them?

**Comment by bbb999** [comment]
Apparently, only in my mind. ;) Pushing, again...

**Comment by matangover** [comment]
Thanks for the prompt fix!! I suggest you apply the same fix to PProPanel-vscode.

**Comment by bbb999** [comment]
Apply to where, exactly?

**Comment by matangover** [comment]
https://github.com/Adobe-CEP/Samples/blob/master/TypeScript/PProPanel-vscode/CSXS/manifest.xml
